FROM node:18.6.0-alpine

LABEL version="1.0"
LABEL description="Development image for the client"

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install && npm cache clean --force

COPY . .

EXPOSE 3000

ENV REACT_APP_API=http://localhost:5000/api

CMD ["npm", "run", "start"]