FROM node:18.6.0-slim

LABEL version="1.0"
LABEL description="Development image for the socket server"

WORKDIR /usr/src/app

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install && npm cache clean --force

COPY . .

RUN npm run build

EXPOSE 8900

CMD ["npm", "run", "start"]