# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:

  server:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Install dependencies
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Install dependencies
        working-directory: ./server
        run: npm i
      
      - name: Build server
        working-directory: ./server
        run: npm run build
    
  client:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Install dependencies
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Install dependencies
        working-directory: ./client
        run: npm install --force
      
      # - name: Build client
      #   working-directory: ./client
      #   run: npm run build

  socket:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Install dependencies
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Install dependencies
        working-directory: ./socket
        run: npm i
      
      - name: Build socket
        working-directory: ./socket
        run: npm run build
